package com.example.myapp.repository;

public enum ScreenEnum {
	ダンジョンスタート("DungeonStart"),
	プレイヤーLV("SetPlayerLV"),
	プレイヤーHP("SetPlayerHP"),
	プレイヤー最大HP("SetPlayerMaxHP"),
	プレイヤー攻撃力("SetPlayerAttack"),
	プレイヤー武器攻撃力("SetPlayerWeaponAttack"),
	プレイヤー強攻撃("SetPlayerCritical"),
	プレイヤーテンション("SetPlayerTension"),
	プレイヤーテンションアップ("UpPlayerTension"),
	プレイヤーテンションダウン("DownPlayerTension"),
	プレイヤーブースト("SetPlayerBoost"),
	ブーストオン("BoostOn"),
	ブーストオフ("BoostOff"),
	プレイヤー武器("SetPlayerWeapon"),
	プレイヤーサブ武器("SetPlayerSubWeapon"),
	武器破壊("BreakWeapon"),
	プレイヤー経験値("SetPlayerEXP"),
	プレイヤー合計経験値("SetPlayerSumEXP"),
	プレイヤーお金("SetPlayerGold"),
	モンスター名("SetMonsterName"),
	モンスターHP("SetMonsterHP"),
	モンスターオーバーHP("SetMonsterOverHP"),
	モンスター攻撃力("SetMonsterAttack"),
	モンスター経験値("SetMonsterEXP"),
	モンスターお金("SetMonsterGold"),
	モンスター回復("SetMonsterHeal"),
	モンスターダメージ("SetMonsterDamage"),
	モンスターダメージ削除("ResetMonsterDamage"),
	モンスター表示("ShowMonster"),
	モンスター再表示("ReShowMonster"),
	モンスター全滅("MonsterDeath"),
	モンスター削除("DeleteMonster"),
	モンスター隠れ("MonsterHidden"),
	モンスターエフェクト("MonsterEffect"),
	モンスターエフェクト削除("DeleteMonsterEffect"),
	ターゲットモンスター("TargetMonster"),
	ボーナスターン("SetMonsterTurn"),
	ボーナスターン消滅("DeleteMonsterTurn"),
	難易度("SetDifficulty"),
	階数("SetSumFloor"),
	合計ターン("SetSumTurn"),
	リザルト("Result"),
	レベルアップメッセージ("LevelUp"),
	次の階("NextFloor"),
	店("Shop"),
	買う("Buy"),
	お金ゲット("GetMoney"),
	お金が足りない("NoEnough"),
	融合画面("FusionMode"),
	融合解除("FusionCancel"),
	カウンター攻撃("CounterAttack"),
	防御成功("DefenceSuccess"),
	アイテム追加("AddItem"),
	アイテム削除("RemoveItem"),
	アイテム表示("ShowItem"),
	アイテム切り替えボタン表示("ShowItemSwitch"),
	アイテム切り替えボタン削除("DeleteItemSwitch"),
	プレイヤーダメージ("PlayerDamage"),
	プレイヤーダメージ削除("DeletePlayerDamage"),
	プレイヤー回復("SetPlayerHeal"),
	アクティブアイテム("ActiveItem"),
	ストップ("Stop"),
	コマンドテキスト("CommandText"),
	攻撃エフェクト("AttackEffect"),
	防御ウェイト("DefenceWait"),
	ウィンドウメッセージ("WindowMessage"),
	プレイヤーコンディションメッセージ("PlayerConditionMessage"),
	モンスターコンディションメッセージ("MonsterConditionMessage"),
	モンスター行動エフェクト("MonsterActionEffect"),
	攻撃を受けた("AttackedEffect"),
	毒を受けた("Poisoned"),
	毒が回復("PoisonHeal"),
	HPが普通("HPNormal"),
	HPが半分以下("HPHalf"),
	HPがピンチ("HPPinch"),
	コカトリスイッチ("CockatriceOn"),
	コカトリスイッチ削除("CockatriceOff"),
	コマンドクリック("CommandClick"),
	クリックサウンド("ClickSound"),
	コマンドOK("CommandOK"),
	待機("Wait"),
	//コマンド許可
	//アイテム許可
	//融合モード
	//店モード
	ダンジョン一覧("DungeonList"),
	デバッグダンジョンリスト("DebugDungeonList"),
	デバッグエンド("DebugEnd"),
	ターンスタート("TurnStart"),
	ゲームオーバー("GameOver"),
	クリア("GameClear"),
	リターン("Return"),
	デバッグプレイヤー("DebugPlayer"),
	デバッグダンジョン("DebugDungeon");
	private String logName;
	
	ScreenEnum(String logName){
		this.logName = logName;
	}
	
	public String getLogName() {
		return logName;
	}
}
